/**
 * Client-side report exports — no backend. Works by reading the report tables
 * rendered inside <main>, so it covers every report page that uses ReportHeader.
 *   - Excel  → .xls (HTML workbook Excel opens natively)
 *   - CSV    → .csv
 *   - PDF    → opens a clean print window → Save as PDF
 */

function reportTables(): HTMLTableElement[] {
  if (typeof document === 'undefined') return [];
  // Report content lives in <main>; the nav/top bar/filters carry no <table>.
  return Array.from(document.querySelectorAll<HTMLTableElement>('main table'));
}

function metaText(): string {
  if (typeof document === 'undefined') return '';
  const h1 = document.querySelector('main h1')?.textContent ?? '';
  const sub = document.querySelector('main h2')?.textContent ?? '';
  return [h1, sub].filter(Boolean).join(' — ');
}

function cellText(el: Element): string {
  return (el.textContent ?? '').replace(/\s+/g, ' ').trim();
}

function tableToMatrix(table: HTMLTableElement): string[][] {
  return Array.from(table.rows).map((row) => Array.from(row.cells).map((c) => cellText(c)));
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function slug(name: string): string {
  return (name || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60) || 'report';
}

/** Build an Excel-openable .xls from all report tables. */
export function exportExcel(title: string) {
  const tables = reportTables();
  if (!tables.length) { exportCsv(title); return; }
  const meta = metaText();
  const body = tables.map((t) => {
    const rows = tableToMatrix(t).map((cells) =>
      `<tr>${cells.map((c) => `<td>${escapeHtml(c)}</td>`).join('')}</tr>`
    ).join('');
    return `<table border="1">${rows}</table><br/>`;
  }).join('');
  const html =
    `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"></head>` +
    `<body><h3>${escapeHtml(meta || title)}</h3>${body}</body></html>`;
  download(new Blob([html], { type: 'application/vnd.ms-excel;charset=utf-8' }), `${slug(title)}.xls`);
}

/** Build a CSV from the report tables (sheets separated by a blank line). */
export function exportCsv(title: string) {
  const tables = reportTables();
  const lines: string[] = [];
  tables.forEach((t, i) => {
    if (i > 0) lines.push('');
    tableToMatrix(t).forEach((cells) => lines.push(cells.map(csvCell).join(',')));
  });
  if (!lines.length) lines.push(metaText() || title);
  download(new Blob(['﻿' + lines.join('\n')], { type: 'text/csv;charset=utf-8' }), `${slug(title)}.csv`);
}

/** Open a clean print window (report tables only) → user picks Save as PDF. */
export function printReport(title: string) {
  const tables = reportTables();
  const meta = metaText();
  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return;
  const tablesHtml = tables.map((t) => t.outerHTML).join('<br/>');
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
    <style>
      *{box-sizing:border-box;}
      body{font-family:Inter,-apple-system,Segoe UI,Roboto,sans-serif;color:#222;padding:32px;}
      h1{font-size:18px;margin:0 0 2px;}
      .meta{font-size:12px;color:#6a6a6a;margin:0 0 18px;}
      table{width:100%;border-collapse:collapse;margin-bottom:18px;font-size:12px;}
      th,td{border-bottom:1px solid #eee;padding:6px 8px;text-align:left;}
      thead th{background:#f7f7f7;font-size:10px;text-transform:uppercase;letter-spacing:.04em;color:#6a6a6a;}
      td:not(:first-child),th:not(:first-child){text-align:right;}
      tbody tr:first-child td{text-align:left;}
      .stamp{margin-top:24px;font-size:10px;color:#b0b0b0;}
    </style></head>
    <body><h1>${escapeHtml(title)}</h1><p class="meta">${escapeHtml(meta)}</p>${tablesHtml}
    <p class="stamp">Generated by StayOps Accounting OS · HOS Management</p></body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 250);
}

export function copyReportLink() {
  if (typeof navigator !== 'undefined' && navigator.clipboard) navigator.clipboard.writeText(window.location.href).catch(() => {});
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function csvCell(s: string): string {
  const v = s.replace(/"/g, '""');
  return /[",\n]/.test(v) ? `"${v}"` : v;
}
