/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/amir/audit`; params?: Router.UnknownInputParams; } | { pathname: `/amir`; params?: Router.UnknownInputParams; } | { pathname: `/amir/profile`; params?: Router.UnknownInputParams; } | { pathname: `/amir/tickets`; params?: Router.UnknownInputParams; } | { pathname: `/sydney`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/profile`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/rooms`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/staff`; params?: Router.UnknownInputParams; } | { pathname: `/amir/ticket/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/amir/audit`; params?: Router.UnknownOutputParams; } | { pathname: `/amir`; params?: Router.UnknownOutputParams; } | { pathname: `/amir/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/amir/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `/sydney`; params?: Router.UnknownOutputParams; } | { pathname: `/sydney/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/sydney/rooms`; params?: Router.UnknownOutputParams; } | { pathname: `/sydney/staff`; params?: Router.UnknownOutputParams; } | { pathname: `/amir/ticket/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/amir/audit${`?${string}` | `#${string}` | ''}` | `/amir${`?${string}` | `#${string}` | ''}` | `/amir/profile${`?${string}` | `#${string}` | ''}` | `/amir/tickets${`?${string}` | `#${string}` | ''}` | `/sydney${`?${string}` | `#${string}` | ''}` | `/sydney/profile${`?${string}` | `#${string}` | ''}` | `/sydney/rooms${`?${string}` | `#${string}` | ''}` | `/sydney/staff${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/amir/audit`; params?: Router.UnknownInputParams; } | { pathname: `/amir`; params?: Router.UnknownInputParams; } | { pathname: `/amir/profile`; params?: Router.UnknownInputParams; } | { pathname: `/amir/tickets`; params?: Router.UnknownInputParams; } | { pathname: `/sydney`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/profile`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/rooms`; params?: Router.UnknownInputParams; } | { pathname: `/sydney/staff`; params?: Router.UnknownInputParams; } | `/amir/ticket/${Router.SingleRoutePart<T>}` | { pathname: `/amir/ticket/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
